name: API CI
on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'
  pull_request:
    paths:
      - 'api/**'

jobs:
  unit-testing:
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Run linting
        run: npm run lint
        shell: bash

      - name: Run unit tests
        run: npm run test:ci
        shell: bash
        env:
          CI: true
          NODE_ENV: test