name: API CI
on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'
  workflow_dispatch:

jobs:
  unit-testing:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: api/package-lock.json
          cache-key: custom-node22-${{ hashFiles('api/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:ci
